// =============================================================================
// GENERATED CARD CONFIG CONTRACT - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================
var CARD_CONFIG_FIELDS = ["entity", "label", "icon", "icon_on", "sensor", "unit", "type", "precision", "options"];
var CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES = ["slider", "light_brightness", "fan_speed"];
var CARD_CONTRACT_FAN_DEFAULT_ICONS = {
  "fan_switch": "Fan Off",
  "fan_speed": "Fan Speed 2",
  "fan_oscillate": "Fan",
  "fan_direction": "Swap Horizontal",
  "fan_preset": "Fan Auto"
};
var CARD_CONTRACT_FAN_DEFAULT_ICON_ON = {
  "fan_switch": "Fan"
};
var CARD_CONTRACT_OPTION_SELECT_ACTION = "input_select.select_option";
var CARD_CONTRACT_OPTION_SELECT_ACTIONS = ["input_select.select_option", "select.select_option"];
var CARD_CONTRACT_SUBPAGE_TYPE_CODES = {
  "action": "A",
  "calendar": "D",
  "timezone": "T",
  "sensor": "S",
  "door_window": "X",
  "weather": "W",
  "weather_forecast": "F",
  "option_select": "U",
  "fan_switch": "B",
  "fan_speed": "J",
  "fan_oscillate": "O",
  "fan_direction": "E",
  "fan_preset": "Z",
  "light_brightness": "V",
  "light_switch": "Q",
  "alarm": "Y",
  "alarm_action": "AA",
  "slider": "L",
  "cover": "C",
  "light_temperature": "N",
  "garage": "R",
  "lock": "K",
  "media": "M",
  "climate": "H",
  "push": "P",
  "internal": "I",
  "subpage": "G"
};
var CARD_CONTRACT_SUBPAGE_TYPES_BY_CODE = {
  "A": "action",
  "D": "calendar",
  "T": "timezone",
  "S": "sensor",
  "X": "door_window",
  "W": "weather",
  "F": "weather_forecast",
  "U": "option_select",
  "B": "fan_switch",
  "J": "fan_speed",
  "O": "fan_oscillate",
  "E": "fan_direction",
  "Z": "fan_preset",
  "V": "light_brightness",
  "Q": "light_switch",
  "Y": "alarm",
  "AA": "alarm_action",
  "L": "slider",
  "C": "cover",
  "N": "light_temperature",
  "R": "garage",
  "K": "lock",
  "M": "media",
  "H": "climate",
  "P": "push",
  "I": "internal",
  "G": "subpage"
};
var CARD_CONTRACT_LARGE_NUMBERS = {
  "sensor": {
    "excludedPrecisions": [
      "text"
    ]
  },
  "weather": {
    "precisions": [
      "today",
      "tomorrow"
    ]
  },
  "calendar": true,
  "timezone": true
};

function cardContractListContains(list, value) {
  return (list || []).indexOf(value) >= 0;
}

function cardContractIsBrightnessSliderType(type) {
  return cardContractListContains(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES, type);
}

function cardContractIsFanCardType(type) {
  return Object.prototype.hasOwnProperty.call(CARD_CONTRACT_FAN_DEFAULT_ICONS, type || "");
}

function cardContractFanDefaultIcon(type) {
  return CARD_CONTRACT_FAN_DEFAULT_ICONS[type] || CARD_CONTRACT_FAN_DEFAULT_ICONS.fan_speed || "Fan Speed 2";
}

function cardContractFanDefaultIconOn(type) {
  return CARD_CONTRACT_FAN_DEFAULT_ICON_ON[type] || "Auto";
}

function cardContractIsOptionSelectType(type) {
  return type === "option_select";
}

function cardContractIsOptionSelectAction(action) {
  return cardContractListContains(CARD_CONTRACT_OPTION_SELECT_ACTIONS, action);
}

function cardContractSubpageTypeCode(type) {
  return CARD_CONTRACT_SUBPAGE_TYPE_CODES[type || ""] || (type || "");
}

function cardContractSubpageTypeFromCode(code) {
  return CARD_CONTRACT_SUBPAGE_TYPES_BY_CODE[code || ""] || (code || "");
}

function cardContractLargeNumbersSupported(type, precision) {
  var rule = CARD_CONTRACT_LARGE_NUMBERS[type || ""];
  if (rule === true) return true;
  if (!rule) return false;
  if (rule.excludedPrecisions) return !cardContractListContains(rule.excludedPrecisions, precision || "");
  if (rule.precisions) return cardContractListContains(rule.precisions, precision || "");
  return false;
}
