#pragma once

// =============================================================================
// GENERATED CARD CONFIG CONTRACT - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

constexpr const char *CARD_CONTRACT_OPTION_SELECT_ACTION = "input_select.select_option";
inline const char *const CARD_CONTRACT_OPTION_SELECT_ACTIONS[] = {"input_select.select_option", "select.select_option"};
inline const char *const CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[] = {"slider", "light_brightness", "fan_speed"};

inline bool card_contract_string_in(const std::string &value, const char *const *items, size_t count) {
  for (size_t i = 0; i < count; i++) {
    if (value == items[i]) return true;
  }
  return false;
}

inline bool card_contract_is_brightness_slider_type(const std::string &type) {
  return card_contract_string_in(type, CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES,
    sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES) / sizeof(CARD_CONTRACT_BRIGHTNESS_SLIDER_TYPES[0]));
}

inline bool card_contract_is_option_select_action(const std::string &action) {
  return card_contract_string_in(action, CARD_CONTRACT_OPTION_SELECT_ACTIONS,
    sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS) / sizeof(CARD_CONTRACT_OPTION_SELECT_ACTIONS[0]));
}

inline bool card_contract_is_fan_card_type(const std::string &type) {
  return type == "fan_switch" ||
         type == "fan_speed" ||
         type == "fan_oscillate" ||
         type == "fan_direction" ||
         type == "fan_preset";
}

inline const char *card_contract_fan_default_icon_name(const std::string &type) {
  if (type == "fan_switch") return "Fan Off";
  if (type == "fan_speed") return "Fan Speed 2";
  if (type == "fan_oscillate") return "Fan";
  if (type == "fan_direction") return "Swap Horizontal";
  if (type == "fan_preset") return "Fan Auto";
  return "Fan Speed 2";
}

inline const char *card_contract_fan_default_icon_on_name(const std::string &type) {
  if (type == "fan_switch") return "Fan";
  return "Auto";
}

inline bool card_contract_large_numbers_supported(const std::string &type, const std::string &precision) {
  if (type == "sensor") return precision != "text";
  if (type == "weather") return precision == "today" || precision == "tomorrow";
  return type == "calendar" || type == "timezone";
}

inline const char *card_contract_subpage_type_code(const std::string &type) {
  if (type == "action") return "A";
  if (type == "calendar") return "D";
  if (type == "timezone") return "T";
  if (type == "sensor") return "S";
  if (type == "door_window") return "X";
  if (type == "weather") return "W";
  if (type == "weather_forecast") return "F";
  if (type == "option_select") return "U";
  if (type == "fan_switch") return "B";
  if (type == "fan_speed") return "J";
  if (type == "fan_oscillate") return "O";
  if (type == "fan_direction") return "E";
  if (type == "fan_preset") return "Z";
  if (type == "light_brightness") return "V";
  if (type == "light_switch") return "Q";
  if (type == "alarm") return "Y";
  if (type == "alarm_action") return "AA";
  if (type == "slider") return "L";
  if (type == "cover") return "C";
  if (type == "light_temperature") return "N";
  if (type == "garage") return "R";
  if (type == "lock") return "K";
  if (type == "media") return "M";
  if (type == "climate") return "H";
  if (type == "push") return "P";
  if (type == "internal") return "I";
  if (type == "subpage") return "G";
  return type.c_str();
}

inline std::string card_contract_subpage_type_from_code(const std::string &code) {
  if (code == "A") return "action";
  if (code == "D") return "calendar";
  if (code == "T") return "timezone";
  if (code == "S") return "sensor";
  if (code == "X") return "door_window";
  if (code == "W") return "weather";
  if (code == "F") return "weather_forecast";
  if (code == "U") return "option_select";
  if (code == "B") return "fan_switch";
  if (code == "J") return "fan_speed";
  if (code == "O") return "fan_oscillate";
  if (code == "E") return "fan_direction";
  if (code == "Z") return "fan_preset";
  if (code == "V") return "light_brightness";
  if (code == "Q") return "light_switch";
  if (code == "Y") return "alarm";
  if (code == "AA") return "alarm_action";
  if (code == "L") return "slider";
  if (code == "C") return "cover";
  if (code == "N") return "light_temperature";
  if (code == "R") return "garage";
  if (code == "K") return "lock";
  if (code == "M") return "media";
  if (code == "H") return "climate";
  if (code == "P") return "push";
  if (code == "I") return "internal";
  if (code == "G") return "subpage";
  return code;
}
