# =============================================================================
# BUILD PROFILE - Waveshare ESP32-S3-Touch-LCD-4.3B (4.3" landscape)
# =============================================================================

substitutions:
  name: "espcontrol-waveshare-43b"
  friendly_name: "Waveshare ESP32-S3-Touch-LCD-4.3B"
  espcontrol_component_url: "file:///config"
  espcontrol_component_ref: "HEAD"

esphome:
  name_add_mac_suffix: true

packages:
  espcontrol: !include ../devices/waveshare-esp32-s3-touch-lcd-4.3b/packages.yaml

wifi:
  ap:
    ssid: "${friendly_name}"

captive_portal:
